# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag pattern on pub.dev: 'v'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: flutter pub publish --force
