# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" # tag pattern on pub.dev: 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze and fix issues
        run: dart fix --apply .

      - name: Publish
        run: flutter pub publish
